<table class="col-md-12">
    <thead>
        <tr>
            <th class="col-md-3">Nazwisko</th>
            <th class="col-md-3">Imię</th>
            <th class="col-md-4">Zespół</th>
            <th class="col-md-1">Edytuj</th>
            <th class="col-md-1">Usuń</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->players as $player): ?>
        <tr>
            <td><?php echo $player->surname ?></td>
            <td><?php echo $player->name ?></td>
            <td><?php echo $player->teamName ?></td>
            <td><a href="/admin/player/edit?id=<?php echo $player->id ?>" title="Edytuj zawodnika">Edytuj</a></td>
            <td><a href="/admin/player/delete?id=<?php echo $player->id ?>" title="Usuń zawodnika">Usuń</a></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>