<?php echo $this->doctype(); ?>
<html>
<head>
    <meta name='author' content='Kamil Małek' />
    <?php echo $this->headMeta(); ?>
    <link rel="shortcut icon" href="<?php echo $this->baseUrl('favicon.ico') ?>" type="image/x-icon">
    <link rel="icon" href="<?php echo $this->baseUrl('favicon.ico') ?>" type="image/x-icon">
    <link href='<?php echo $this->baseUrl('css/bootstrap.css') ?>' rel='stylesheet' type='text/css' />
    <link href='<?php echo $this->baseUrl('css/admin.css') ?>' rel='stylesheet' type='text/css' />
    <script src="<?php echo $this->baseUrl('js/jquery.min.js') ?>"></script>
    <script src='<?php echo $this->baseUrl('js/bootstrap.js') ?>'></script>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('js/datetimepicker/jquery.datetimepicker.css') ?>" />
    <script src="<?php echo $this->baseUrl('js/datetimepicker/build/jquery.datetimepicker.full.js') ?>"></script>
    <script>
        $(document).ready(function() {
            $('input[type=datetime]').datetimepicker({
                lang: 'pl',
                step: 10,
                dayOfWeekStart: 1,
                format: 'Y-m-d H:i:00'
            });
            $('input[type=date]').datetimepicker({
                lang: 'pl',
                timepicker: false,
                format: 'Y-m-d'
            });
        })
    </script>
    <?php echo $this->headTitle(); ?>
</head>
<body>
    <div class="container" id="login">
        <?php
            echo $this->form;
        ?>
        <?php if($this->error): ?>
            <div class="alert alert-danger" role="alert">
                <?php echo $this->error; ?>
            </div>
        <?php endif; ?>
        <?php if($this->success): ?>
            <div class="alert alert-success" role="alert">
                <?php echo $this->success; ?>
            </div>
        <?php endif; ?>
    </div>
</body>
</html>