<?php if ($this->pageCount): ?>
<div class="paginationControl">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('page' => $this->previous),'index_page'); ?>">
    &lt; Poprzednia strona
  </a>
<?php else: ?>
  <span class="disabled">&lt; Poprzednia strona</span>
<?php endif; ?>
 
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="<?php echo $this->url(array('page' => $page),'index_page'); ?>">
        <?php echo $page; ?>
    </a>
  <?php else: ?>
    <span><?php echo $page; ?></span>
  <?php endif; ?>
<?php endforeach; ?>
 
<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->next),'index_page'); ?>">
    Następna strona &gt;
  </a>
<?php else: ?>
  <span class="disabled">Następna strona &gt;</span>
<?php endif; ?>
</div>
<?php endif; ?>