<div class="site col-md-12">
    <div class="title">
        <h1>Kadra zespołu Kilo Wiejskiej</h1>
    </div>
    <div class="separator"></div>
    <div class="content">
        <?php foreach($this->players as $player): ?>
            <div class="player col-md-5 col-md-offset-1">
                <div class="player_photo col-xs-4">
                    <img src="<?php $photo = $player->photo != null ? $player->photo : 'player.png'; echo $this->baseUrl('img/kw/player/'.$photo); ?>" alt="Player" />
                </div>
                <div class="player_info col-xs-8">
                    <div class="player_personal">
                        <div class="player_name"><?php echo $player->name.' '.$player->surname ?></div>
                        <div class="separator"></div>
                        <div class="player_position"><?php echo $player->position ?></div>
                        <div class="player_age">wiek: <?php echo $player->age ?></div>
                        <div class="player_height">wzrost: <?php echo $player->height ? $player->height.' cm' : '-' ?></div>
                        <div class="player_weight">waga: <?php echo $player->weight ? $player->weight.' kg' : '-' ?></div>
                        <div class="player_city">miejsce zamieszkania: <?php echo $player->city ?></div>
                    </div>
                    <div class="player_stats">
                        <div class="player_stat col-xs-3">
                            <img src="<?php echo $this->baseUrl('img/favicon.png') ?>" alt="Występy" />
                            <?php echo $player->performances!= null ? $player->performances : 0; ?>
                        </div>
                        <div class="player_stat col-xs-3">
                            <img src="<?php echo $this->baseUrl('img/favicon.png') ?>" alt="Bramki" />
                            <?php echo $player->goals!= null ? $player->goals : 0; ?>
                        </div>
                        <div class="player_stat col-xs-3">
                            <img src="<?php echo $this->baseUrl('img/favicon.png') ?>" alt="Żółte kartki" />
                            <?php echo $player->cards!= null ? $player->cards : 0; ?>
                        </div>
                        <div class="player_stat col-xs-3">
                            <img src="<?php echo $this->baseUrl('img/favicon.png') ?>" alt="Czerwone kartki" />
                            <?php echo $player->cards!= null ? $player->cards : 0; ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>