<div class="site col-md-12">
    <div class="title">
        <h1>Kadra zespołu Kilo Wiejskiej</h1>
    </div>
    <div class="separator"></div>
    <div class="content">
        <?php foreach($this->players as $player): ?>
            <div class="player">
                <div class="player_photo col-md-2 col-xs-4">
                    <img src="<?php echo $player->photo != null ? $player->photo : 'img/player.png'; ?>" alt="Player" />
                </div>
                <div class="player_info col-md-4 col-xs-8">
                    <div class="player_personal">
                        <div class="player_name"><?php echo $player->name.' '.$player->surname ?></div>
                        <div clas="player_position"><?php echo $player->position ?></div>
                        <div class="separator"></div>
                        <div class="player_age">wiek: <?php echo $player->age ?></div>
                        <div class="player_city">miejsce zamieszkania: <?php echo $player->city ?></div>
                    </div>
                </div>
                <div class="player_stats col-md-6 col-xs-12">
                    <div class="player_stat col-xs-4">
                        <span class="player_stat_count"><?php echo $player->performances!= null ? $player->performances : 0; ?></span>
                        występów
                    </div>
                    <div class="player_stat col-xs-4">
                        <span class="player_stat_count"><?php echo $player->cards!= null ? $player->cards : 0; ?></span>
                        kartek
                    </div>
                    <div class="player_stat col-xs-4">
                        <span class="player_stat_count"><?php echo $player->goals!= null ? $player->goals : 0; ?></span>
                        bramek
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>