<!doctype html>
<html>
<head>
	<meta charset='utf-8' />
	<meta name='author' content='Kamil Małek' />
	<link href='css/style.css' rel='stylesheet' type='text/css' />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<title>Intro</title>
</head>
<body class="intro">
	<div class="container">
		<img src="img/logo_kwft.png" alt="KWFT" />
		<div class="intro_content">
			Stowarzyszenie <br /> <strong>Kilo Wiejskiej Futsal Team</strong>
			<div id="motto">Kilo Wiejskiej to coś więcej niż drużyna - to styl życia.</div>
			<div class="separator"></div>
			<button>Strona oficjalna</button>
			<button>Gminna Liga Wakacyjna</button>
		</div>
	</div>
</body>
</html>