<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <link href='<?php echo $this->baseUrl('css/bootstrap.css') ?>' rel='stylesheet' type='text/css' />
    <link href='<?php echo $this->baseUrl('css/error.css') ?>' rel='stylesheet' type='text/css' />
    <title><?php echo $this->message ?></title>
</head>
<body>
    <div id="error">
        <img src="<?php echo $this->baseUrl('img/kwft_215.png'); ?>" alt="Kilo Wiejskiej Futsal Team" />
        <?php
            if ($this->exception) {
                $this->message = $this->exception->getMessage();
            }
        ?>
        <h2><?php echo $this->message ?></h2>
        <a href="/" title="Wróć do strony głównej" >Wróć do strony głównej</a>
    </div>

</body>
</html>
