<table id="matches" class="col-md-12">
    <thead>
        <tr>
            <th class="col-md-1">Kolejka</th>
            <th class="col-md-3">Data</th>
            <th class="col-md-2">Gospodardz</th>
            <th class="col-md-2">Gość</th>
            <th class="col-md-1">Wynik</th>
            <th class="col-md-1">Edytuj</th>
            <th class="col-md-1">Uzupełnij zawodników</th>
            <th class="col-md-1">Usuń</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->matches as $match): ?>
        <tr>
            <td><?php echo $match->stage ?></td>
            <td><?php echo $match->date ?></td>
            <td><?php echo $match->home_name ?></td>
            <td><?php echo $match->away_name ?></td>
            <td><?php echo $match->is_played ? $match->home_goals.':'.$match->away_goals : '-:-' ?></td>
            <td><a href="/admin/match/edit?id=<?php echo $match->id ?>" title="Edytuj mecz" >Edytuj</a></td>
            <td><a href="/admin/match/fill?id=<?php echo $match->id ?>" title="Uzupełnij mecz" >Uzupełnij</a></td>
            <td><a href="/admin/match/delete?id=<?php echo $match->id ?>" title="Edytuj mecz" >Usuń</a></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>