<?php echo $this->doctype(); ?>
<html>
<head>
    <meta name='author' content='Kamil Małek' />
    <?php echo $this->headMeta(); ?>
    <link rel="shortcut icon" href="<?php echo $this->baseUrl('favicon.ico') ?>" type="image/x-icon">
    <link rel="icon" href="<?php echo $this->baseUrl('favicon.ico') ?>" type="image/x-icon">
    <link href='<?php echo $this->baseUrl('css/bootstrap.css') ?>' rel='stylesheet' type='text/css' />
    <link href='<?php echo $this->baseUrl('css/admin.css') ?>' rel='stylesheet' type='text/css' />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('js/datetimepicker/jquery.datetimepicker.css') ?>" />
    <script src="<?php echo $this->baseUrl('js/jquery.min.js') ?>"></script>
    <script src='<?php echo $this->baseUrl('js/bootstrap.js') ?>'></script>
    <script src='<?php echo $this->baseUrl('js/admin_panel.js') ?>'></script>
    <script src='<?php echo $this->baseUrl('js/tinymce/tinymce.min.js') ?>'></script>
    <script src="<?php echo $this->baseUrl('js/datetimepicker/build/jquery.datetimepicker.full.js') ?>"></script>
    <script>
        $(document).ready(function() {
            $('input[type=datetime]').datetimepicker({
                lang: 'pl',
                step: 10,
                dayOfWeekStart: 1,
                format: 'Y-m-d H:i:00'
            });
            $('input[type=date]').datetimepicker({
                lang: 'pl',
                timepicker: false,
                format: 'Y-m-d'
            });
        })
    </script>
    <script>
        tinymce.init({
            selector:'textarea',
            language: "pl",
            height: 200,
            plugins: [
                "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
                "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
                "save table contextmenu directionality emoticons template paste textcolor"
            ],
            toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media | forecolor backcolor emoticons"
        });
    </script>
    <?php echo $this->headTitle(); ?>
</head>
<body>
    <div class="admin_panel col-md-2">
        <div id="kw_logo">
            <img src="<?php echo $this->baseUrl('img/kwft_65.png'); ?>" alt="Stowarzyszenie Kilo Wiejskiej Futsal Team"/>
        </div>
        <ul id="panels">
            <li>
                <div>Artykuły</div>
                <ul>
                    <li><a href="/admin/news" title="Artykuły">Lista</a></li>
                    <li><a href="/admin/news/add" title="Dodaj artykuł">Dodaj artykuł</a></li>
                </ul>
            </li>
            <li>
                <div>Kategorie</div>
                <ul>
                    <li><a href="/admin/category" title="Kategorie">Lista</a></li>
                    <li><a href="/admin/category/add" title="Dodaj kategorię">Dodaj kategorię</a></li>
                </ul>
            </li>
            <li>
                <div>Strony</div>
                <ul>
                    <li><a href="/admin/site" title="Strony">Lista</a></li>
                    <li><a href="/admin/site/add" title="Dodaj stronę">Dodaj stronę</a></li>
                </ul>
            </li>
            <li>
                <div>Użytkownicy</div>
                <ul>
                    <li><a href="/admin/user" title="Użytkownicy">Lista</a></li>
                </ul>
            </li>
            <p></p>
            <li>
                <div>Drużyny</div>
                <ul>
                    <li><a href="/admin/team" title="Drużyny">Lista</a></li>
                    <li><a href="/admin/team/add" title="Dodaj drużynę">Dodaj drużynę</a></li>
                </ul>
            </li>
            <li>
                <div>Mecze</div>
                <ul>
                    <li><a href="/admin/match" title="Mecze">Lista</a></li>
                    <li><a href="/admin/match/add" title="Dodaj mecz">Dodaj mecz</a></li>
                </ul>
            </li>
            <li>
                <div>Sezony</div>
                <ul>
                    <li><a href="/admin/season" title="Sezony">Lista</a></li>
                    <li><a href="/admin/season/add" title="Dodaj sezon">Dodaj sezon</a></li>
                </ul>
            </li>
            <li>
                <div>Zawodnicy</div>
                <ul>
                    <li><a href="/admin/player" title="Zawodnicy">Lista</a></li>
                    <li><a href="/admin/player/add" title="Dodaj zawodnika">Dodaj zawodnika</a></li>
                </ul>
            </li>
        </ul>
        <a href="/admin/index/logout" title="Wyloguj się" id="logout_link">
            <div id="logout">
                <img src="<?php echo $this->baseUrl('img/logout.png'); ?>" alt="Wyloguj się"/>
                <div>Wyloguj się</div>
            </div>
        </a>
    </div>
    <div class="content col-md-10">
        <?php echo $this->layout()->content; ?>
    </div>
</body>
</html>