<?php echo $this->doctype(); ?>
<html>
<head>
    <meta name='author' content='Kamil Małek' />
    <?php echo $this->headMeta(); ?>
    <link rel="shortcut icon" href="<?php echo $this->baseUrl('favicon.ico') ?>" type="image/x-icon">
    <link rel="icon" href="<?php echo $this->baseUrl('favicon.ico') ?>" type="image/x-icon">
    <link href='<?php echo $this->baseUrl('css/bootstrap.css') ?>' rel='stylesheet' type='text/css' />
    <link href='<?php echo $this->baseUrl('css/admin.css') ?>' rel='stylesheet' type='text/css' />
    <script src="<?php echo $this->baseUrl('js/jquery.min.js') ?>"></script>
    <script src='<?php echo $this->baseUrl('js/bootstrap.js') ?>'></script>
    <script src='<?php echo $this->baseUrl('js/admin_panel.js') ?>'></script>
    <?php echo $this->headTitle(); ?>
</head>
<body>
    <div class="admin_panel col-md-2">
        <ul id="panels">
            <li>
                <div>Artykuły</div>
                <ul>
                    <li><a href="/admin/news" title="Artykuły">Lista</a></li>
                    <li><a href="/admin/news/add" title="Dodaj artykuł">Dodaj artykuł</a></li>
                </ul>
            </li>
            <li>
                <div>Kategorie</div>
                <ul>
                    <li><a href="/admin/category" title="Kategorie">Lista</a></li>
                    <li><a href="/admin/category/add" title="Dodaj kategorię">Dodaj kategorię</a></li>
                </ul>
            </li>
            <li>
                <div>Strony</div>
                <ul>
                    <li><a href="/admin/site" title="Strony">Lista</a></li>
                    <li><a href="/admin/site/add" title="Dodaj stronę">Dodaj stronę</a></li>
                </ul>
            </li>
            <li>
                <div>Użytkownicy</div>
                <ul>
                    <li><a href="/admin/user" title="Użytkownicy">Lista</a></li>
                </ul>
            </li>
            <p></p>
            <li>
                <div>Drużyny</div>
                <ul>
                    <li><a href="/admin/team" title="Drużyny">Lista</a></li>
                    <li><a href="/admin/team/add" title="Dodaj drużynę">Dodaj drużynę</a></li>
                </ul>
            </li>
            <li>
                <div>Mecze</div>
                <ul>
                    <li><a href="/admin/match" title="Mecze">Lista</a></li>
                    <li><a href="/admin/match/add" title="Dodaj mecz">Dodaj mecz</a></li>
                </ul>
            </li>
            <li>
                <div>Sezony</div>
                <ul>
                    <li><a href="/admin/season" title="Sezony">Lista</a></li>
                    <li><a href="/admin/season/add" title="Dodaj sezon">Dodaj sezon</a></li>
                </ul>
            </li>
            <li>
                <div>Zawodnicy</div>
                <ul>
                    <li><a href="/admin/player" title="Zawodnicy">Lista</a></li>
                    <li><a href="/admin/player/add" title="Dodaj zawodnika">Dodaj zawodnika</a></li>
                </ul>
            </li>
        </ul>
    </div>
    <div class="content col-md-10">
        <?php echo $this->layout()->content; ?>
    </div>
</body>
</html>