<?php echo $this->doctype(); ?>
<html>
<head>
    <meta name='author' content='Kamil Małek' />
    <?php echo $this->headMeta(); ?>
    <link rel="shortcut icon" href="<?php echo $this->baseUrl('favicon.ico') ?>" type="image/x-icon">
    <link rel="icon" href="<?php echo $this->baseUrl('favicon.ico') ?>" type="image/x-icon">
    <link href='<?php echo $this->baseUrl('css/bootstrap.css') ?>' rel='stylesheet' type='text/css' />
    <link href='<?php echo $this->baseUrl('css/style.css') ?>' rel='stylesheet' type='text/css' />
    <script src="<?php echo $this->baseUrl('js/jquery.min.js') ?>"></script>
    <script src='<?php echo $this->baseUrl('js/bootstrap.js') ?>'></script>
    <?php echo $this->headTitle(); ?>
</head>
<body>
    <div id="fb-root"></div>
    <script>
        window.fbAsyncInit = function() {
          FB.init({
            appId      : '1652268505057180',
            xfbml      : true,
            version    : 'v2.5'
          });
        };

        (function(d, s, id){
           var js, fjs = d.getElementsByTagName(s)[0];
           if (d.getElementById(id)) {return;}
           js = d.createElement(s); js.id = id;
           js.src = "//connect.facebook.net/pl_PL/sdk.js";
           fjs.parentNode.insertBefore(js, fjs);
         }(document, 'script', 'facebook-jssdk'));
      </script>
    <div class="fb">
        <div class="fb-page" data-href="https://www.facebook.com/Kilo-Wiejskiej-210043922347916/" data-width="350" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true" data-show-posts="false"></div>
        <div class="fb-icon"></div>
    </div>
    
    <?php echo $this->menu(); ?>

    <div class="main content">
        <div class="container">
            <?php echo $this->layout()->content; ?>
        </div>
    </div>

    <?php echo $this->render('footer.phtml') ?>

</body>
</html>