<?php echo $this->doctype(); ?>
<html>
<head>
    <meta name='author' content='Kamil Małek' />
    <?php echo $this->headMeta(); ?>
    <link href='css/bootstrap.css' rel='stylesheet' type='text/css' />
    <link href='css/style.css' rel='stylesheet' type='text/css' />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src='js/bootstrap.js'></script>
    <?php echo $this->headTitle(); ?>
</head>
<body>
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                    <img src="img/logo_kwft.png" alt="Stowarzyszenie Kilo Wiejskiej Futsal Team" width="65px" style="float: left; margin-right: 20px;"/>
                    Stowarzyszenie <br /> Kilo Wiejskiej Futsal Team
                </a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="active"><a href="/index">Strona główna</a></li>
                    <li><a href="o-nas.html">O nas</a></li>
                    <li><a href="sklad.html">Skład</a></li>
                    <li><a href="multimedia.html">Multimedia</a></li>
                    <li><a href="kontakt.html">Kontakt</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="content container">
        <?php echo $this->layout()->content; ?>
    </div>

    <footer class="footer">
        <div class="container">
            <div class="footer_description col-md-4">
                <span class="span_kilo">Kilo Wiejskiej</span> to coś więcej niż drużyna - to styl życia.
                <div class="separator"></div>
                <div>Amatorska drużyna Kilo Wiejskiej powstała w 2011 roku z inicjatywy Damiana Łąkasa i swój debiut zaliczyła na turnieju w Sierosławicach (woj. Małopolskie). Zespół specjalizuje się głównie w piłce nożnej halowej.</div>
                <button>Dowiedz się więcej</button>
            </div>
            <div class="footer_logo col-md-4">
                <img src="img/logo_kwft.png" alt="KWFT" width="250px" />
            </div>
            <div class="footer_events col-md-4">
                <div style="margin-bottom: 20px">Najbliższe turnieje organizowane przez <span class="span_kilo">Kilo Wiejskiej</span>:</div>
                <table class="footer_events_table">
                    <tr>
                        <td>Turniej Mikołajkowy</td>
                        <td>06.12.2015 r.</td>
                    </tr>
                    <tr>
                        <td>Liga Wakacyjna Glewiec</td>
                        <td>24.05.2016 r.</td>
                    </tr>
                </table>
                <div class="separator"></div>
                <table class="made_by">
                    <tr>
                        <td>CMS & Develop</td>
                        <td>Kamil Małek</td>
                    </tr>
                    <tr>
                        <td>Design</td>
                        <td>Piotr Pabiś</td>
                    </tr>
                </table>
            </div>
        </div>
    </footer>

</body>
</html>